import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className='xl:px-44 px-4 md:px-24 sm:px-20'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className='flex flex-col place-items-center py-28'>
        <h2 className='text-xl font-bold text-center mb-2'>Ayo Serviskan Barang Elektronikmu Yang Rusak di 
        <span className='text-brand'> Rozy Elektronik</span>
        </h2>
        <h2 className='text-sm bg-zinc-100 p-1 font-thin'>Tempat Servis Terjamin & Bergaransi</h2>
        <Image className='my-10'
        src={"assets/elektronik.svg"}
        width={300}
        height={500}
        alt="elektronik"
        />
      </div>
    </div>
  )
}

const revalidate = 10;
export default Home
